<a href="https://colab.research.google.com/github/brenomgp/aulaflask/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

O QUE É UM ARRAY?
tipos de array : ndarrays -> significam arrays com any dimensões 
1-D array -> possui apenas uma dimensão. sera comumente chamado de vector ou vetor
2-D array -> possui 2 dimensões. sera comumente chamado matriz ou matrix
3-D array -> possui 3 ou mais dimensões. sera comumente chamado de tensor 

In [ ]:
import numpy as np

np.array


In [ ]:
)a = np.array([9, 8, 7, 6, 5, 4])
print(a)
print(type(a)


[9 8 7 6 5 4]
<class 'numpy.ndarray'>


np.zeros

In [ ]:
zero_array = np.zeros(shape = (4,3,5))
print(zero_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


np.ones

In [ ]:
um_array = np.ones(5)
print(um_array)

[1. 1. 1. 1. 1.]


In [ ]:
um_array = np.ones((2,3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
vazio_array = np.empty(1)
print(vazio_array)

[1.]


In [ ]:
zero_dez = np.arange(10)
print(zero_dez)
pula_dois = np.arange(3,15,2)
print(pula_dois)

[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13]


In [ ]:
array_linear = np.linspace(0, 200, num = 20, endpoint = False )
print(array_linear)


[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120. 130.
 140. 150. 160. 170. 180. 190.]


In [ ]:
array_linear = np.linspace(0, 200, num = 20, endpoint = True )
print(array_linear)



[  0.          10.52631579  21.05263158  31.57894737  42.10526316
  52.63157895  63.15789474  73.68421053  84.21052632  94.73684211
 105.26315789 115.78947368 126.31578947 136.84210526 147.36842105
 157.89473684 168.42105263 178.94736842 189.47368421 200.        ]


In [ ]:
array_linear = np.linspace(0, 200, num = 20, endpoint = False, retstep = True )
print(array_linear)


(array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140., 150., 160., 170., 180., 190.]), 10.0)


In [ ]:
zero_array = np.zeros(shape = (4,5,6))
print(zero_array)


[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [ ]:
print(zero_array.shape)
print(zero_array.size)
print(zero_array.ndim)

(4, 5, 6)
120
3
